### ISSUE TITLE
Scenario group is not needed anymore

### ISSUE THREAD

**Issue by kidzik** [kidzik/orchestration-graphs#11]
Since in one scenario we can enclose several paths at once, we don't need the notion of 'scenario group' any more.

**Comment by thibaultcalvayrac** [comment]
@ritterni could you remove the group from the Scenario model ? We tried to do it with @rphkhr but we don't really know how to make the migrations 😿

**Comment by ritterni** [comment]
Done. For future reference making migrations is easy, you just have to run `manage.py makemigrations`.
