### ISSUE TITLE
Can't add activities to scenario after editing

### ISSUE THREAD

**Issue by ritterni** [kidzik/orchestration-graphs#19]
If you right-click and edit an activity in the scenario editor it then becomes impossible to add other activities.

**Comment by rphkhr** [comment]
Thanks for bringing this to us; We're in the middle of refactoring all the code concerning scenario editor, and it should fixed in our next commit (Should be tomorrow night maximum)

**Comment by thibaultcalvayrac** [comment]
Closed by 65d7aae7fa936a943a2e9324e9cde92f40302f95
