### ISSUE TITLE
Scenario fails when referring to activity that doesn't exist in database

### ISSUE THREAD

**Issue by rphkhr** [kidzik/orchestration-graphs#4]
Should deleting an activity delete all graphs containing the activity? Right now, deleting an activity makes scenarios remove all subsequent activities:
If ScenarioA goes 1-2-3, and we delete 2, scenarioA will only show 1 on Preview

**Comment by thibaultcalvayrac** [comment]
For now, we should probably just prevent activity deletion if it belongs to one of the existing scenari
