### ISSUE TITLE
Editing activities should behave differently depending on type

### ISSUE THREAD

**Issue by ritterni** [kidzik/orchestration-graphs#6]
The activity editor works well for link activities, but it's not quite adapted to other types of activities.

Text activities: The 'source' input could be a larger text box since this field is supposed to contain text. It could also be labelled as 'content' or something instead.

Quiz and psycho activities: The 'source' field isn't used by these activities. Their data is stored as 'Question' objects in the database. I don't know if making a full quiz editor is really within the scope of this project though, so maybe just grey out the source box, and remove quiz and psycho from the 'create activity' menu (since the resulting quiz would be empty anyway).

**Comment by thibaultcalvayrac** [comment]
We will simply change the activity editor this way:
- If editing an existing activity, the type field is disabled
- If creating a new activity, the type field can only be 'text' or 'link'
- If the edited activity is 'quiz' or 'psycho', only the name, group and description can be changed
- If the edited/created activity is 'text' or 'link', the source (content) can also be changed
